language: python

install:
  - pip install tox

script:
  - tox

env:
  - TOXENV=py27-django17
  - TOXENV=py27-django18
  - TOXENV=py34-django17
  - TOXENV=py34-django18
  - TOXENV=coverage

after_success: coveralls